### ISSUE TITLE
Mod no longer works as new game version was released (V45)

### ISSUE THREAD

**Issue by Lefruite1337** [legoandmars/BiggerLobby#10]
Traceback:
[Error : Unity Log] AmbiguousMatchException: Ambiguous match found.
Stack trace:
System.RuntimeType.GetMethodImplCommon (System.String name, System.Int32 genericParameterCount, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) (at <787acc3c9a4c471ba7d971300105af24>:0)
HarmonyLib.AccessTools.DeclaredMethod (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchTools.GetOriginalMethod (HarmonyLib.HarmonyMethod attr) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Ambiguous match for HarmonyMethod[(class=HUDManager, methodname=SyncAllPlayerLevelsServerRpc, type=Normal, args=undefined)]
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
BiggerLobby.Plugin.Awake () (at :0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

Game was updated several minutes ago and mod no longer works. Lobby instantly crashes on player connect.

**Comment by Fingarde** [comment]
Hey,
Until the mod is fixed you can play with the previous version

To do this, you must activate it in Property > Beta > previous

Update the game and enjoy !

**Comment by Rhalith** [comment]
It gives null reference exception at "SetPlayerVoiceFilters(ref SoundManager __instance)" when try to invite player.

**Comment by legoandmars** [comment]
Should be fixed in 2.5.0, although there's still a pretty nasty bug in basegame, i'll copy this here for prudence


# ⚠️ TEMPORARY ULTRA MEGA SUPER COMPATIBILITY WARNING (IMPORTANT)
Right now in v45, there's a base game bug that breaks the game when anybody disconnects or gets kicked.

This leads to public lobbies breaking often generally, but especially if you're trying to get 40 people into one lobby.

As of the time of writing, this bug applies to all lobbies (Vanilla, BiggerLobby, MoreCompany, etc). Please be warned you **will** have to restart if anybody disconnects, or attempts to join with the wrong mod version.

This will apply until this is fixed in the base game, or a workaround is found, at which point this warning will be removed.

**Comment by legoandmars** [comment]
Kick bug fixed in basegame, closing as completed
